# -- Affinity labels for pod assignment
affinity: {}

fullNameOverride: ""

image:
  # -- Image pull policy
  pullPolicy: IfNotPresent

  # -- Image repository
  repository: openvpn/openvpn-as

  # -- Image tag
  tag: ""

# -- Registry secret names as an array
imagePullSecrets: []

# -- Ingress configuration
ingress:
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  # -- Enable ingress resource for Client UI
  enabled: false

  # -- Host for the ingress
  hostName: client.openvpn.local

  # -- Set ingressClassName here, or leave it unset
  ingressClassName:

  tls:
    # -- Enable TLS configuration for the hostname defined at ingress.hostName parameter
    enabled: true
    secretName: client.openvpn-tls

nameOverride: ""

# -- Node labels for pod assignment
nodeSelector: {}

persistence:
  # -- PVC Access Mode for volume
  accessMode: "ReadWriteOnce"

  # -- Annotations for the PVC
  annotations: {}

  # -- Enable persistence using PVC
  enabled: true

  # -- used when PVC already created before install
  existingClaimName:

  # -- Indicate another subpath for licenses storage
  licensesSubpath: licenses

  # -- PVC Storage Request for volume
  size: "8Gi"

  # -- PVC Storage Class for volume
  storageClass:

# -- Map of annotations to add to the pods
podAnnotations: {}

# -- Map of pod security context values
podSecurityContext: {}

replicaCount: 1

# -- CPU/Memory resource requests/limits
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Security Context
securityContext:

  capabilities:

    add: ["NET_ADMIN"]

service:

  # -- Kubernetes Service type for Client UI
  type: ClusterIP

  # -- VPN TCP port
  vpnTcpPort: 443

  # -- VPN UDP port
  vpnUdpPort: 1194

  # -- Client UI port
  vpnUiPort: 943

serviceAccount:
  # -- Annotations for the service account.
  annotations: {}

  # -- Create ServiceAccount
  create: true

  # -- Name to give the service account.
  name: ""

# -- The timezone that should be used.
timezone: Etc/UTC

# -- Tolerations for for the pod.
tolerations: []
