apiVersion: v2
# App version is meaningless since this is a generic chart.
appVersion: "0.0.0"
description: A Helm chart for deploying generic API services to Kubernetes.
icon: https://helm.sh/img/helm.svg
name: generic-api-service
type: application
version: 0.1.2
