#!/bin/bash

set -e -o pipefail

echo "Running pre-commit checks..."
echo

# From https://stackoverflow.com/a/4774063
REPO_DIR="$( cd -- "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P )"

cd "$REPO_DIR"

[ -s venv/bin/activate ] && source venv/bin/activate

# Echo commands as they're executed.
set -x

make style

make quality

make docs
