apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "openvpn-as.labels" . | nindent 4 }}
  name: {{ include "openvpn-as.full-name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "openvpn-as.selector-labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openvpn-as.selector-labels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: TZ
          value: {{ default "Etc/UTC" .Values.timezone | quote}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.vpnTcpPort }}
          name: vpn-tcp
          protocol: TCP
        - containerPort: {{ .Values.service.vpnUdpPort }}
          name: vpn-udp
          protocol: UDP
        - containerPort: {{ .Values.service.vpnUiPort }}
          name: vpn-ui
          protocol: TCP
        livenessProbe:
          exec:
            command: ["/usr/local/openvpn_as/scripts/sacli", "Status"]
          initialDelaySeconds: 100
          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 100
          tcpSocket:
            port: {{ .Values.service.vpnUiPort }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /openvpn
          name: persistence
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openvpn-as.service-account-name" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: persistence
        persistentVolumeClaim:
          {{- if .Values.persistence.existingClaimName }}
          claimName: {{ .Values.persistence.existingClaimName }}
          {{- else }}
          claimName: {{ include "openvpn-as.full-name" . }}-data
          {{- end }}
