name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Write permission needed for chart-releaser to push tags, create
      # releases, and publish the index to gh-pages.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - env:
          RELEASE_ACTOR_NAME_FROM_REPO: "${{ vars.RELEASE_ACTOR_NAME }}"
          RELEASE_ACTOR_EMAIL_FROM_REPO: "${{ vars.RELEASE_ACTOR_EMAIL }}"
        name: Configure Git
        run: |
          RELEASE_ACTOR_NAME="${RELEASE_ACTOR_NAME_FROM_REPO:-$GITHUB_ACTOR}"
          RELEASE_ACTOR_EMAIL="${RELEASE_ACTOR_EMAIL_FROM_REPO:-$GITHUB_ACTOR@users.noreply.github.com}"
          git config user.name "$RELEASE_ACTOR_NAME"
          git config user.email "$RELEASE_ACTOR_EMAIL"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.3

      - env:
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
